import Link from "next/link";
import { ArrowRight, MapPin } from "lucide-react";
import { TripMap } from "@/components/map/trip-map";
import { PostCard } from "@/components/blog/post-card";
import { SubscribeForm } from "@/components/forms/subscribe-form";
import { siteConfig } from "@/config/site";
import { getPublishedPosts } from "@/lib/posts";
import { formatDate } from "@/lib/utils";
import { getTripMapState, getTripStats } from "@/lib/trip-stats";
import { PostCover } from "@/components/blog/post-cover";

export default async function Home() {
  const [publishedPosts, tripStats, tripMapState] = await Promise.all([getPublishedPosts(), getTripStats(), getTripMapState()]);
  const latest = publishedPosts[0];
  return <>
    <section className="retro-hero page-shell mt-6 sm:mt-10"><div className="retro-titlebar"><span>ROAD_LOG.HTML</span><span>— □ ×</span></div><div className="retro-hero-body"><div><p className="retro-trip-badge"><span aria-hidden="true">★</span> 5 MONTH ROAD TRIP <span aria-hidden="true">★</span></p><h1 className="font-serif text-[clamp(2.8rem,8vw,6.2rem)] font-semibold leading-[.96] tracking-[-.035em] text-forest">{siteConfig.tripName}</h1><div className="retro-stats-grid mt-8" aria-label="Trip statistics">{tripStats.map((stat) => <div className="retro-stat" key={stat.label}><strong>{stat.value}</strong><span>{stat.label}</span></div>)}</div><div className="retro-trip-formula"><p className="retro-formula-label">{"// THE ROAD-TRIP FORMULA"}</p><p className="retro-formula-input">Town &amp; Country 2010 Minivan <b>+</b> 300k Miles <b>+</b> Moving to El Paso <b>+</b> Career Change <b>+</b> 2 Kind Uncles</p><div className="retro-formula-rule" aria-hidden="true" /><p className="retro-formula-output"><span>=</span> Roleplaying as a Long Haul Trucker</p></div></div></div><div className="retro-statusbar"><span>● ONLINE FROM {tripMapState.currentLocationName.toUpperCase()}</span><span>YOU ARE VISITOR #001432</span></div></section>
    <section id="route" className="retro-window page-shell mt-12 scroll-mt-24 sm:mt-16"><div className="retro-section-head flex flex-wrap items-center justify-between gap-3"><h2>★ Follow the journey</h2><p className="retro-current flex items-center gap-2"><span className="h-2 w-2 animate-pulse rounded-full bg-[#33cc66]" />Currently near {tripMapState.currentLocationName}</p></div><div className="p-2 sm:p-3"><TripMap posts={publishedPosts} tripState={tripMapState} /></div></section>
    <section id="subscribe" className="retro-daily-signup page-shell mt-14 scroll-mt-24 sm:mt-20" aria-labelledby="daily-signup-heading"><div className="retro-daily-label"><span>✉</span> INBOX_TRANSMISSION.EXE <span className="retro-daily-blink">●</span></div><div className="retro-daily-body"><div><p className="retro-daily-kicker">FREE ROAD-SIDE UPDATES</p><h2 id="daily-signup-heading">Follow the Journey Daily</h2><p>Get each new journal entry delivered straight from the road.</p></div><div className="retro-daily-form"><SubscribeForm /></div></div><div className="retro-daily-status"><span>STATUS: ACCEPTING NEW TRAVEL BUDDIES</span><span>NO SPAM · EASY UNSUBSCRIBE</span></div></section>
    <section className="readable-surface page-shell mb-12 mt-14 py-8 sm:mb-16 sm:mt-20 sm:py-10" aria-labelledby="latest-heading"><div className="retro-section-label mb-4"><span>NEW!</span> Fresh from the road</div><h2 id="latest-heading" className="mb-5 font-serif text-3xl font-semibold text-forest sm:text-4xl">Most recent entry</h2>{latest ? <article className="retro-feature grid overflow-hidden bg-white lg:grid-cols-[1.15fr_.85fr]"><div className="relative min-h-72 lg:min-h-[470px]"><PostCover src={latest.coverImage} alt={latest.coverImageAlt} priority /></div><div className="flex flex-col justify-center p-7 sm:p-10 lg:p-12"><p className="text-xs font-bold uppercase tracking-[.14em] text-sage">Day {latest.tripDay} · {formatDate(latest.entryDate)}</p><h3 className="mt-4 font-serif text-4xl font-semibold leading-tight text-forest">{latest.title}</h3><p className="mt-4 flex items-center gap-2 text-sm font-semibold text-stone-500"><MapPin size={16} />{latest.locationName}</p><p className="mt-5 text-lg leading-8 text-stone-600">{latest.excerpt}</p><Link href={`/journal/${latest.slug}`} className="button-primary mt-7 self-start gap-2">Read full entry <ArrowRight size={17} /></Link></div></article> : <div className="border-2 border-dashed border-sage bg-white p-8 text-center text-stone-600">The first road entry will appear here once it is published.</div>}</section>
    <section id="journal" className="retro-journal-box retro-window page-shell my-12 scroll-mt-24 sm:my-16"><div className="retro-titlebar"><span>THE_ROAD_JOURNAL.HTML</span><span>— □ ×</span></div><div className="p-6 sm:p-9"><div className="mb-8 max-w-2xl"><p className="retro-section-label inline-block">{">> NOTES ALONG THE WAY"}</p><h2 className="mt-3 font-serif text-4xl font-semibold text-forest sm:text-5xl">The road journal</h2><p className="mt-4 text-lg leading-8 text-stone-600">Small moments, long views, and honest notes from life between stops.</p></div>{publishedPosts.length > 1 ? <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{publishedPosts.slice(1).map((post) => <PostCard post={post} key={post.id} />)}</div> : <p className="border-2 border-dashed border-sage bg-white p-6 text-stone-600">More journal entries will collect here as the trip continues.</p>}</div><div className="retro-statusbar"><span>JOURNAL ARCHIVE: ONLINE</span><span>{publishedPosts.length} {publishedPosts.length === 1 ? "ENTRY" : "ENTRIES"} SAVED</span></div></section>
  </>;
}
