"use client";

import { useActionState,useState } from "react";
import { submitComment,type CommentState } from "@/app/journal/comment-actions";

export interface PublicComment{id:string;displayName:string;body:string;createdAt:string}
export function Comments({postId,slug,comments}:{postId:string;slug:string;comments:PublicComment[]}){const [state,action,pending]=useActionState(submitComment,{message:"",success:false} as CommentState);const [startedAt]=useState(()=>Date.now());return <section aria-labelledby="comments-heading" className="mt-16 border-t border-stone-200 pt-12"><h2 id="comments-heading" className="font-serif text-3xl font-semibold text-forest">Campfire comments</h2><p className="mt-2 text-stone-600">Leave a note for the road. Comments are reviewed before appearing.</p>
  {comments.length>0?<div className="mt-8 space-y-5">{comments.map((comment)=><article key={comment.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex items-baseline justify-between gap-3"><h3 className="font-bold text-forest">{comment.displayName}</h3><time dateTime={comment.createdAt} className="text-xs text-stone-500">{new Date(comment.createdAt).toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"})}</time></div><p className="mt-2 whitespace-pre-wrap leading-7 text-stone-700">{comment.body}</p></article>)}</div>:<p className="mt-6 border-2 border-dashed border-sage bg-white p-4 text-sm text-stone-600">No approved comments yet. Be the first to leave a note.</p>}
  {state.success?<div role="status" className="mt-8 rounded-2xl border border-sage/30 bg-[#e9eee5] p-5"><p className="font-bold text-forest">{state.message}</p></div>:<form action={action} className="mt-8 rounded-3xl border border-stone-200 bg-[#f4f0e7] p-5 sm:p-7"><input type="hidden" name="postId" value={postId}/><input type="hidden" name="slug" value={slug}/><input type="hidden" name="startedAt" value={startedAt}/><div className="absolute -left-[9999px]" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div><div><label className="form-label" htmlFor={`displayName-${postId}`}>Display name</label><input className="form-input bg-white" id={`displayName-${postId}`} name="displayName" maxLength={60} required/></div><div className="mt-4"><label className="form-label" htmlFor={`commentBody-${postId}`}>Comment</label><textarea className="form-input min-h-32 resize-y bg-white" id={`commentBody-${postId}`} name="body" maxLength={1200} required/></div>{state.message&&<p role="alert" className="mt-3 text-sm font-bold text-red-800">{state.message}</p>}<button type="submit" className="button-primary mt-5" disabled={pending}>{pending?"Submitting…":"Submit for review"}</button></form>}
  </section>}
