"use server";

import { createHash,randomBytes } from "node:crypto";
import { createClient } from "@/lib/supabase/server";
import { subscribeSchema } from "@/validation/forms";
import { sendEmail } from "@/lib/email";
import { normalizePhoneNumber, sendMms } from "@/lib/twilio";

export interface SubscribeState{message:string;success:boolean}
export async function subscribe(_state:SubscribeState,formData:FormData):Promise<SubscribeState>{const parsed=subscribeSchema.safeParse({name:formData.get("name")||undefined,email:formData.get("email"),phone:formData.get("phone"),smsConsent:formData.get("smsConsent")});if(!parsed.success)return{message:parsed.error.issues[0]?.message??"Check your details.",success:false};const phone=parsed.data.smsConsent?normalizePhoneNumber(parsed.data.phone):null;if(parsed.data.smsConsent&&!phone)return{message:"Enter a valid U.S. mobile number, including area code.",success:false};const token=randomBytes(32).toString("hex");const hash=createHash("sha256").update(token).digest("hex");const supabase=await createClient();const {error}=await supabase.rpc("subscribe_to_trip",{p_email:parsed.data.email,p_name:parsed.data.name??"",p_confirmation_token_hash:hash,p_phone_e164:phone,p_sms_consent:parsed.data.smsConsent});if(error)return{message:"Subscription could not be saved. This email or phone may already be registered.",success:false};const siteUrl=process.env.NEXT_PUBLIC_SITE_URL??"http://localhost:3000";const emailResult=await sendEmail(parsed.data.email,"Confirm your road-trip updates",`<h1>One quick confirmation</h1><p>Confirm that you want new road journal entries by email.</p><p><a href="${siteUrl}/subscribe/confirm?token=${token}">Confirm subscription</a></p>`);const details=[emailResult.sent?"Check your email to confirm email updates.":"Email confirmation is pending setup."];if(phone){const textResult=await sendMms(phone,"Curtis Road Trip (Road & Country): You’re enrolled in recurring road-journal text/MMS alerts. Message frequency varies. Msg & data rates may apply. Reply HELP for help or STOP to opt out.");details.push(textResult.sent?"A text confirmation is on its way.":"Text delivery is pending setup.");}return{message:details.join(" "),success:true};}
